apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ray-system

resources:
- ../../apiserver/deploy/base
- ../../ray-operator/config/rbac
- ../../ray-operator/config/manager

images:
- name: kuberay/apiserver
  newName: kuberay/apiserver
  newTag: v0.6.0
- name: kuberay/operator
  newName: kuberay/operator
  newTag: v0.6.0

